### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by GouravSardana** [sugarlabs/SugarLabs_Social#9]
@samswag @quozl
Can I add Search bar in Feeds?
I will implement the search bar in jquery and It will search according to title name !
Looking Forward to your reply!

**Comment by quozl** [comment]
Please, don't make it a habit to ask for permission.  That's not how we work.  See [guide to contributing](https://github.com/sugarlabs/sugar-docs/blob/83b48f99ee267917909897c7a40b8ab7d3373f86/src/contributing.md) for more on that.

My own preference is that you work on Music Blocks (JavaScript), Sugarizer (JavaScript), or Sugar and activities (Python and JavaScript).  Your work on Sugar Labs Social won't immediately benefit Sugar Labs, because it isn't being used, in turn because we have so few developers who want to work on the Sugar Labs software.

However, @avinashbharti97 has asked for this repository in your [earlier issue](https://github.com/sugarlabs/social/issues/2) that you
> don't start coding for features without getting a green signal to your proposed feature by mentor of this project.  Mentors are: Samson Goddy, Hrishi Patel, Jaskirat Singh, Pericherla Seetaramaraju.

An unusual requirement contrary to our usual culture, but there are probably good reasons to coordinate carefully on something that isn't yet being used.
